### PR TITLE
Added background for Alpha, new shapes for preference and custom summary

### PR DESCRIPTION
**Pull request by J-Jamet**
Hi MrBIMC,

I added functionality to your awesome project : 
- Background draughtboard for alpha color
- New shapes (Square and Rounded_square) for preference preview
- Summary with [color] tag for add in custom string

And I have resolved bug of landscape.

Can you add them to the main project and make a new version for gradle ?
Thanks :)

### CODE REVIEW

**Comment by J-Jamet** [comment]
I think you should have looked at the changes made and make a branch for the pull request. I asked for it a year ago, and I made a lot of changes.

**Comment by MrBIMC** [comment]
yeah, i accidentally accepted all of them xD. Anyway, I'll revert changes
and will cherry pick them 1 by 1. Thank you for your commitment!

чт, 23 мар. 2017 г. в 14:52, Jérémy JAMET <notifications@github.com>:

**Comment by J-Jamet** [comment]
Sorry for you and it will be long. :/ I changed the name of packages to my organization's name (for open softwares) and I started to replace your views by fragments. If you have any questions do not hesitate. After we can work together it can be cool. But since I have several projects at the same time, we must organize ourselves.

**Comment by kengraWin** [comment]
oh

**Pull request merged**
